@VeterinaryClinicManagementSystem_HostAddress = http://localhost:5171

GET {{VeterinaryClinicManagementSystem_HostAddress}}/api/Pets
Accept: application/json

###

POST {{VeterinaryClinicManagementSystem_HostAddress}}/api/Pets
Content-Type: application/json

{
  "id" : 1,
  "name" : "Ellie",
  "species" : "Canine",
  "breed" : "JRT-Poodle",
  "sex" : "Female",
  "birthdate" : "2020-06-26"
}

###

POST {{VeterinaryClinicManagementSystem_HostAddress}}/api/Owners
Content-Type: application/json

{
  "id" : 1,
  "name" : "Jerome Penaflor",
  "address" : "General Trias, Cavite",
  "contactNumber" : "09278792601"
}

###
