@VeterinaryClinicManagementSystem_HostAddress = http://localhost:5171

GET {{VeterinaryClinicManagementSystem_HostAddress}}/api/Pets
Accept: application/json

###

GET {{VeterinaryClinicManagementSystem_HostAddress}}/api/Pets/3
Accept: application/json

###

GET {{VeterinaryClinicManagementSystem_HostAddress}}/api/Owners
Accept: application/json

###
GET {{VeterinaryClinicManagementSystem_HostAddress}}/api/Veterinarians
Accept: application/json

###

POST {{VeterinaryClinicManagementSystem_HostAddress}}/api/Pets
Content-Type: application/json

{
  "name" : "Ellie",
  "species" : "Canine",
  "breed" : "JRT-Poodle",
  "sex" : "Female",
  "birthdate" : "2020-06-26"
}

###

POST {{VeterinaryClinicManagementSystem_HostAddress}}/api/Pets/3/Vaccinations
Content-Type: application/json

{
  "name" : "8in1",
  "dateAdministered" : "2021-03-02"
}

###

POST {{VeterinaryClinicManagementSystem_HostAddress}}/api/Owners
Content-Type: application/json

{
  "name" : "Jerome Penaflor",
  "address" : "General Trias, Cavite",
  "contactNumber" : "0999999927"
}

###

POST {{VeterinaryClinicManagementSystem_HostAddress}}/api/Veterinarians
Content-Type: application/json

{
  "name" : "Levi Penaflor",
  "contactNumber" : "0927870000"
}

###

POST {{VeterinaryClinicManagementSystem_HostAddress}}/api/Owners/1/Pets/2

###

POST {{VeterinaryClinicManagementSystem_HostAddress}}/api/Pets/1/Veterinarians/1

###

DELETE {{VeterinaryClinicManagementSystem_HostAddress}}/api/Pets/1/
